apiVersion: v1
kind: Service
metadata:
  labels:
    app: kayak-service
  name: kayak-service
spec:
  ports:
    - name: http
      port: 8000
  selector:
    app: kayak-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kayak-service
  name: kayak-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kayak-service
  template:
    metadata:
      labels:
        app: kayak-service
    spec:
      containers:
        - image: jonidocker/kayak-app:1.0
          name: kayak-app
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGODB_HOST
              value: mongodb
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
              initialDelaySeconds: 5
              periodSeconds: 5